# Use the official Node.js image as a base
FROM node:20 AS node-build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port your Node.js app runs on
EXPOSE 3000

# Command to run the Node.js app
CMD ["npm", "start"]
