services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
   
  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"  # Expose Flask app port
    volumes:
      - ./images:/app/images
